### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by YannickB** [OCA/vertical-community#10]
Hello everyone,

I am currently creating the labels for the issues. I already created some of them but if you have some ideas please suggest them them here.

Process new feature : 
-Issue open by contributors
-Add wishlist label
-Discussion until we know exactly what shall be done
-Add specified label, and eventually High or Normal label
-When someone propose to develop it, we assign the ticket to him with a milestone.
-Once developed, add needs review label
-Once reviewed and integrated in the main branch, we can close the ticket

Bugs : 
-Issue open by contributor
-If reproductible, add confirmed label
-When someone propose to develop it, we assign the ticket to him with a milestone.
-Once developed, add needs review label
-Once reviewed and integrated in the main branch, we can close the ticket

What do you think?

**Comment by lucode** [comment]
I think that's a good starting point. I would ad maybe _marketplace_ and _transaction_.

**Comment by lucode** [comment]
I don't know how to  label an issue?

**Comment by YannickB** [comment]
I don't think it's a good idea to use specific features like marketplace and transaction as label, we should concentrate on state but I may be wrong.

It seems only user with write access on the repo can label issues

**Comment by YannickB** [comment]
As said by @yvaucher in the other ticket, the list of issues in OCA is listed here : 

https://github.com/OCA/maintainers-tools/blob/master/tools/set_repo_labels.py

I was looking for this information but didn't found it, I'll rename the labels now.

**Comment by YannickB** [comment]
Ok we now have the label of the OCA, and also : 
normal
high
specified
wishlist

I think this shall be enough for now, I close the ticket.
