### ISSUE TITLE
TODO: Sync labels

### ISSUE THREAD

**Issue by yvaucher** [OCA/vertical-community#16]
Many labels are missing and I see new ones.
It is preferable to have same logic in all OCA repo.

https://github.com/OCA/maintainers-tools/blob/master/tools/set_repo_labels.py

If some labels are missing, you can still suggest new ones.

**Comment by yvaucher** [comment]
@YannickB just saw your issue https://github.com/OCA/vertical-community/issues/10

**Comment by YannickB** [comment]
Duplicate I close, thanks for the information through.
