### ISSUE TITLE
Error in Marketplace single Item view

### ISSUE THREAD

**Issue by lucode** [OCA/vertical-community#24]
The follwing Server  Error occurs when I try to open a single item in the Marketplace.
Previous the actual update it was fine.

> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo-server/openerp/http.py", line 517, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 538, in dispatch
>     result = self._call_function(*_self.params)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 294, in _call_function
>     return checked_call(self.db, *args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
>     return f(dbname, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 291, in checked_call
>     return self.endpoint(_a, *_kw)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 754, in __call__
>     return self.method(_args, *_kw)
>   File "/opt/odoo/odoo-server/openerp/http.py", line 387, in response_wrap
>     response = f(_args, *_kw)
>   File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 949, in call_kw
>     return self._call_kw(model, method, args, kwargs)
>   File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 941, in _call_kw
>     return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/addons/mail/mail_thread.py", line 344, in fields_view_get
>     res = super(mail_thread, self).fields_view_get(cr, uid, view_id=view_id, view_type=view_type, context=context, toolbar=toolbar, submenu=submenu)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/models.py", line 1550, in fields_view_get
>     xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 836, in postprocess_and_fields
>     self.raise_view_error(cr, user, message, view_id, context)
>   File "/opt/odoo/odoo-server/openerp/api.py", line 237, in wrapper
>     return old_api(self, _args, *_kwargs)
>   File "/opt/odoo/odoo-server/openerp/addons/base/ir/ir_ui_view.py", line 367, in raise_view_error
>     raise AttributeError(message)
> AttributeError: Das Feld `delivery_date` existiert nicht
> 
> Fehler Kontext:Ansicht `marketplace.announcement.form`
> [view_id: 763, xml_id: marketplace.view_marketplace_announcement_form, model: marketplace.announcement, parent_id: k. A.]

**Comment by florent-valeureux** [comment]
I remember this issue. It was fixed with this commit@60dfa447c438159360d26071084de45cc4a7bee5

**Comment by lucode** [comment]
Sorry I had to update my databases first. Now the error is gone.
